# Generated by Django 4.2.8 on 2024-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, unique=True, verbose_name='вопрос')),
                ('target_score', models.IntegerField(verbose_name='Таргетированный показатель')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.AlterModelOptions(
            name='indicators',
            options={'verbose_name': 'Индикатор', 'verbose_name_plural': 'Индикаторы'},
        ),
        migrations.AlterField(
            model_name='indicators',
            name='question',
            field=models.CharField(max_length=300, unique=True, verbose_name='Вопрос'),
        ),
        migrations.AlterModelTable(
            name='indicators',
            table='indicator',
        ),
    ]
