# Generated by Django 4.2.8 on 2024-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100, verbose_name='актив')),
                ('age', models.IntegerField(verbose_name='Возраст компании')),
                ('d_div_e', models.FloatField(verbose_name='Отношение долга компании к ее капиталу (D/E)')),
                ('eps', models.FloatField(verbose_name='Чистая прибыль на 1 акцию (EPS)')),
                ('p_div_e', models.FloatField(verbose_name='Переоценка акций (P/E)')),
                ('p_div_bv', models.FloatField(verbose_name='Отношение капитализации к собственному капиталу (P/BV)')),
                ('p_div_s', models.FloatField(verbose_name='Отношение капиталищации к общей выручке(P/S)')),
                ('ev_div_ebitda', models.FloatField(verbose_name='Отношение стоимости компании к прибыли (EV/EBITDA)')),
                ('roe', models.FloatField(verbose_name='Чистая прибыль к собственному капиталу (ROE)')),
                ('roa', models.FloatField(verbose_name='Чистая прибыль к средней стоимости активов (ROA)')),
                ('roe_min_roa_abs', models.FloatField(verbose_name='Абсолютная разница ROE и ROA')),
                ('gross_margin', models.FloatField(verbose_name='Валовая прибыль к выручке gross margin')),
                ('ncav', models.FloatField(verbose_name='Чистая стоимость активов компании (NCAV)')),
                ('asset_diff', models.FloatField(verbose_name='Изменение цены акции за последний год (%)')),
            ],
            options={
                'verbose_name': 'Бумага',
                'verbose_name_plural': 'Бумаги',
                'db_table': 'asset',
            },
        ),
    ]
